import { ToolItem } from '../types';

export const TOOLS_LIST: ToolItem[] = [
  // --- AI TOOLS ---
  {
    id: 'ai-chat',
    name: 'AI Chat Assistant',
    description: 'Smart conversational AI assistant powered by Gemini 2.5 Flash for answering questions & coding.',
    category: 'ai',
    icon: 'MessageSquare',
    tags: ['chat', 'assistant', 'gemini', 'qa'],
    isAi: true,
    rating: 4.9,
    usageCount: 14200,
    popular: true,
  },
  {
    id: 'ai-writer',
    name: 'AI Content Writer',
    description: 'Generate high quality articles, blogs, essays and long-form prose with customizable tone.',
    category: 'ai',
    icon: 'PenTool',
    tags: ['writer', 'article', 'essay', 'content'],
    isAi: true,
    rating: 4.8,
    usageCount: 9800,
    popular: true,
  },
  {
    id: 'ai-rewriter',
    name: 'AI Content Rewriter',
    description: 'Paraphrase, rephrase, and elevate existing paragraphs for clarity, flow, and tone.',
    category: 'ai',
    icon: 'RefreshCw',
    tags: ['paraphrase', 'rewrite', 'rephrase'],
    isAi: true,
    rating: 4.7,
    usageCount: 7600,
  },
  {
    id: 'ai-summarizer',
    name: 'AI Text Summarizer',
    description: 'Condense articles, reports, or documents into executive summaries and bullet points.',
    category: 'ai',
    icon: 'FileText',
    tags: ['summary', 'condense', 'tldr'],
    isAi: true,
    rating: 4.9,
    usageCount: 11200,
    popular: true,
  },
  {
    id: 'ai-translator',
    name: 'AI Multi-Language Translator',
    description: 'Translate text seamlessly across 50+ languages with contextual accuracy.',
    category: 'ai',
    icon: 'Languages',
    tags: ['translate', 'languages', 'bengali', 'hindi', 'spanish'],
    isAi: true,
    rating: 4.8,
    usageCount: 8900,
  },
  {
    id: 'ai-grammar',
    name: 'AI Grammar & Style Checker',
    description: 'Fix typos, punctuation errors, grammatical flaws, and receive stylistic suggestions.',
    category: 'ai',
    icon: 'CheckCheck',
    tags: ['grammar', 'spellcheck', 'editing'],
    isAi: true,
    rating: 4.9,
    usageCount: 13100,
    popular: true,
  },
  {
    id: 'ai-email-writer',
    name: 'AI Email Generator',
    description: 'Draft polite, formal, cold outreach, or client response emails in seconds.',
    category: 'ai',
    icon: 'Mail',
    tags: ['email', 'outreach', 'formal'],
    isAi: true,
    rating: 4.7,
    usageCount: 6500,
  },
  {
    id: 'ai-resume-builder',
    name: 'AI Resume & CV Generator',
    description: 'Create tailored ATS-friendly bullet points and summary sections for your career resume.',
    category: 'ai',
    icon: 'FileBadge',
    tags: ['resume', 'cv', 'career', 'ats'],
    isAi: true,
    isPremium: true,
    rating: 4.9,
    usageCount: 9400,
    popular: true,
  },
  {
    id: 'ai-cover-letter',
    name: 'AI Cover Letter Writer',
    description: 'Generate personalized job application pitch cover letters for targeted roles.',
    category: 'ai',
    icon: 'FileSignature',
    tags: ['coverletter', 'job', 'application'],
    isAi: true,
    rating: 4.8,
    usageCount: 5400,
  },
  {
    id: 'ai-caption-gen',
    name: 'AI Social Caption Generator',
    description: 'Create viral captions, emojis, and hashtags for Instagram, TikTok, LinkedIn, and Twitter.',
    category: 'ai',
    icon: 'Share2',
    tags: ['social', 'instagram', 'hashtags', 'caption'],
    isAi: true,
    rating: 4.7,
    usageCount: 8100,
  },
  {
    id: 'ai-prompt-gen',
    name: 'AI Prompt Builder',
    description: 'Engineered prompts for Midjourney, DALL-E 3, ChatGPT, and Stable Diffusion.',
    category: 'ai',
    icon: 'Zap',
    tags: ['prompt', 'midjourney', 'dalle'],
    isAi: true,
    rating: 4.8,
    usageCount: 7200,
  },
  {
    id: 'ai-blog-writer',
    name: 'AI Full Blog Post Generator',
    description: 'Generate complete SEO-optimized blog posts with headings, outline, and conclusion.',
    category: 'ai',
    icon: 'Newspaper',
    tags: ['blog', 'seo', 'article'],
    isAi: true,
    isPremium: true,
    rating: 4.9,
    usageCount: 10500,
  },
  {
    id: 'ai-story-writer',
    name: 'AI Fiction & Story Creator',
    description: 'Craft engaging creative stories, sci-fi, drama, or fantasy narratives with custom genres.',
    category: 'ai',
    icon: 'BookOpen',
    tags: ['story', 'fiction', 'novel'],
    isAi: true,
    rating: 4.6,
    usageCount: 4300,
  },
  {
    id: 'ai-script-writer',
    name: 'AI Video Script Writer',
    description: 'Generate structured video scripts with visual cues for YouTube, Shorts, and Reels.',
    category: 'ai',
    icon: 'Video',
    tags: ['script', 'youtube', 'reels', 'tiktok'],
    isAi: true,
    rating: 4.8,
    usageCount: 6100,
  },
  {
    id: 'ai-code-gen',
    name: 'AI Code Generator',
    description: 'Generate clean React, TypeScript, Python, SQL, C++, Java or HTML/CSS code.',
    category: 'ai',
    icon: 'Code',
    tags: ['code', 'python', 'react', 'typescript'],
    isAi: true,
    rating: 4.9,
    usageCount: 15600,
    popular: true,
  },
  {
    id: 'ai-debugger',
    name: 'AI Code Debugger',
    description: 'Paste error stack traces or buggy code snippets to receive immediate fixes.',
    category: 'ai',
    icon: 'Bug',
    tags: ['debug', 'error', 'fix', 'code'],
    isAi: true,
    rating: 4.8,
    usageCount: 8400,
  },
  {
    id: 'ai-sql-gen',
    name: 'AI Natural Language to SQL',
    description: 'Convert English queries into production-ready SQL statements for Postgres, MySQL & SQLite.',
    category: 'ai',
    icon: 'Database',
    tags: ['sql', 'database', 'postgres', 'mysql'],
    isAi: true,
    rating: 4.7,
    usageCount: 5200,
  },
  {
    id: 'ai-regex-gen',
    name: 'AI Regex Generator & Explainer',
    description: 'Construct regular expressions from plain text descriptions with syntax breakdown.',
    category: 'ai',
    icon: 'Binary',
    tags: ['regex', 'pattern', 'text'],
    isAi: true,
    rating: 4.8,
    usageCount: 4900,
  },
  {
    id: 'ai-ocr',
    name: 'AI Vision OCR (Image to Text)',
    description: 'Upload images, receipts, or document photos to extract structured text using Gemini AI Vision.',
    category: 'ai',
    icon: 'Eye',
    tags: ['ocr', 'image-text', 'vision', 'scan'],
    isAi: true,
    isPremium: true,
    rating: 4.9,
    usageCount: 11800,
    popular: true,
  },
  {
    id: 'ai-speech-to-text',
    name: 'AI Voice to Text Transcriber',
    description: 'Speak into your microphone or upload speech to get high-accuracy text transcriptions.',
    category: 'ai',
    icon: 'Mic',
    tags: ['voice', 'speech', 'audio', 'transcribe'],
    isAi: true,
    rating: 4.7,
    usageCount: 6800,
  },
  {
    id: 'ai-text-to-speech',
    name: 'AI Text to Speech Reader',
    description: 'Convert written text into natural-sounding voice audio with adjustable speed & pitch.',
    category: 'ai',
    icon: 'Volume2',
    tags: ['tts', 'voice', 'audio', 'speech'],
    isAi: true,
    rating: 4.8,
    usageCount: 7900,
  },
  {
    id: 'ai-image-desc',
    name: 'AI Image Analyzer & Tag Generator',
    description: 'Get detailed visual descriptions, accessibility alt text, and meta tags for images.',
    category: 'ai',
    icon: 'Image',
    tags: ['image', 'vision', 'alttext', 'analysis'],
    isAi: true,
    rating: 4.6,
    usageCount: 4100,
  },
  {
    id: 'ai-pdf-chat',
    name: 'AI PDF Document Q&A',
    description: 'Upload PDF content or paste documents to ask questions, extract facts & study notes.',
    category: 'ai',
    icon: 'FileQuestion',
    tags: ['pdf', 'chatpdf', 'qna', 'document'],
    isAi: true,
    isPremium: true,
    rating: 4.9,
    usageCount: 16200,
    popular: true,
  },

  // --- PDF TOOLS ---
  {
    id: 'pdf-merge',
    name: 'Merge PDF Documents',
    description: 'Combine multiple PDF files into one single organized PDF file.',
    category: 'pdf',
    icon: 'FilePlus',
    tags: ['pdf', 'merge', 'combine'],
    rating: 4.9,
    usageCount: 18400,
    popular: true,
  },
  {
    id: 'pdf-split',
    name: 'Split PDF Pages',
    description: 'Divide a large PDF into separate files or custom page ranges.',
    category: 'pdf',
    icon: 'Scissors',
    tags: ['pdf', 'split', 'cut', 'pages'],
    rating: 4.8,
    usageCount: 12100,
  },
  {
    id: 'pdf-compress',
    name: 'Compress PDF Size',
    description: 'Reduce PDF file size while maintaining visual quality for email & web uploads.',
    category: 'pdf',
    icon: 'FileArchive',
    tags: ['pdf', 'compress', 'reduce'],
    rating: 4.8,
    usageCount: 15300,
    popular: true,
  },
  {
    id: 'pdf-text-to-pdf',
    name: 'Text & Document to PDF Converter',
    description: 'Convert formatted plain text or Word notes directly into a downloadable PDF.',
    category: 'pdf',
    icon: 'FileType',
    tags: ['pdf', 'word', 'text', 'convert'],
    rating: 4.7,
    usageCount: 8800,
  },
  {
    id: 'pdf-pdf-to-text',
    name: 'PDF Text Extractor',
    description: 'Extract raw text content from PDF documents for easy copying and editing.',
    category: 'pdf',
    icon: 'FileSpreadsheet',
    tags: ['pdf', 'extract', 'text'],
    rating: 4.7,
    usageCount: 9100,
  },
  {
    id: 'pdf-image-to-pdf',
    name: 'Images (JPG/PNG) to PDF',
    description: 'Combine multiple image files into a high quality PDF presentation or document.',
    category: 'pdf',
    icon: 'ImagePlus',
    tags: ['pdf', 'jpg-pdf', 'images'],
    rating: 4.9,
    usageCount: 14700,
    popular: true,
  },
  {
    id: 'pdf-watermark',
    name: 'Watermark & Protect PDF',
    description: 'Add custom text watermarks, stamp logos, or date stamps onto PDF pages.',
    category: 'pdf',
    icon: 'Stamp',
    tags: ['pdf', 'watermark', 'protect'],
    rating: 4.7,
    usageCount: 6200,
  },
  {
    id: 'pdf-rotate',
    name: 'Rotate PDF Pages',
    description: 'Rotate PDF pages 90, 180, or 270 degrees clockwise or counterclockwise.',
    category: 'pdf',
    icon: 'RotateCw',
    tags: ['pdf', 'rotate', 'orient'],
    rating: 4.8,
    usageCount: 5900,
  },
  {
    id: 'pdf-extract-pages',
    name: 'Extract PDF Pages',
    description: 'Select and save specific page numbers from a document into a new PDF.',
    category: 'pdf',
    icon: 'Layers',
    tags: ['pdf', 'pages', 'extract'],
    rating: 4.8,
    usageCount: 7300,
  },

  // --- IMAGE TOOLS ---
  {
    id: 'img-bg-remover',
    name: 'AI Background Mask & Eraser',
    description: 'Remove background colors and isolate subject elements using canvas masking.',
    category: 'image',
    icon: 'Eraser',
    tags: ['bgremover', 'background', 'transparent', 'png'],
    rating: 4.9,
    usageCount: 19800,
    popular: true,
  },
  {
    id: 'img-compressor',
    name: 'Image Compressor & Optimizer',
    description: 'Compress PNG, JPG, or WEBP image file sizes with real-time quality slider preview.',
    category: 'image',
    icon: 'Minimize2',
    tags: ['compress', 'optimize', 'png', 'jpg'],
    rating: 4.9,
    usageCount: 16500,
    popular: true,
  },
  {
    id: 'img-resizer',
    name: 'Image Resizer & Scaler',
    description: 'Resize image dimensions by pixels or percentage with aspect ratio lock.',
    category: 'image',
    icon: 'Scaling',
    tags: ['resize', 'dimensions', 'width', 'height'],
    rating: 4.8,
    usageCount: 11200,
  },
  {
    id: 'img-cropper',
    name: 'Interactive Image Crop Tool',
    description: 'Crop images to exact aspect ratios like 1:1 square, 16:9 landscape, 9:16 story, or custom.',
    category: 'image',
    icon: 'Crop',
    tags: ['crop', 'aspect', 'square'],
    rating: 4.8,
    usageCount: 9400,
  },
  {
    id: 'img-converter',
    name: 'Format Converter (JPG, PNG, WEBP)',
    description: 'Convert image files instantly between JPG, PNG, and modern WEBP web formats.',
    category: 'image',
    icon: 'RefreshCcw',
    tags: ['convert', 'jpg', 'png', 'webp'],
    rating: 4.9,
    usageCount: 13800,
  },
  {
    id: 'img-enhancer',
    name: 'Image Filter & Photo Enhancer',
    description: 'Adjust brightness, contrast, saturation, sharpness, warm tones, and vintage filters.',
    category: 'image',
    icon: 'Sliders',
    tags: ['enhance', 'filter', 'photo', 'adjust'],
    rating: 4.7,
    usageCount: 8200,
  },
  {
    id: 'img-blur',
    name: 'Background Blur Tool',
    description: 'Apply soft gaussian radial blur effects or privacy blurs to sensitive areas.',
    category: 'image',
    icon: 'Aperture',
    tags: ['blur', 'portrait', 'privacy'],
    rating: 4.6,
    usageCount: 5100,
  },
  {
    id: 'img-watermark-remover',
    name: 'Spot Touch-up & Spot Eraser',
    description: 'Interactive canvas brush tool to clone and touch up unwanted artifacts or spots.',
    category: 'image',
    icon: 'Paintbrush',
    tags: ['touchup', 'eraser', 'spot', 'clean'],
    rating: 4.7,
    usageCount: 7100,
  },
  {
    id: 'img-qr-scanner',
    name: 'QR Code & Barcode Image Scanner',
    description: 'Upload image files or use web camera to decode embedded QR links and barcodes.',
    category: 'image',
    icon: 'QrCode',
    tags: ['qr', 'scanner', 'barcode', 'decode'],
    rating: 4.8,
    usageCount: 9900,
  },

  // --- TEXT TOOLS ---
  {
    id: 'text-word-counter',
    name: 'Word, Character & Sentence Counter',
    description: 'Analyze word count, character count, reading time, speaking duration, and sentence structure.',
    category: 'text',
    icon: 'Hash',
    tags: ['words', 'counter', 'characters', 'stats'],
    rating: 4.9,
    usageCount: 17200,
    popular: true,
  },
  {
    id: 'text-case-converter',
    name: 'Case Converter Tool',
    description: 'Convert text instantly to UPPERCASE, lowercase, Title Case, camelCase, kebab-case & snake_case.',
    category: 'text',
    icon: 'Type',
    tags: ['case', 'uppercase', 'lowercase', 'camelcase'],
    rating: 4.8,
    usageCount: 10400,
  },
  {
    id: 'text-duplicate-remover',
    name: 'Duplicate Line & List Remover',
    description: 'Clean up text lists by removing duplicate lines, empty spacing, or sorting alphabetically.',
    category: 'text',
    icon: 'ListFilter',
    tags: ['duplicates', 'cleaner', 'dedupe'],
    rating: 4.7,
    usageCount: 6700,
  },
  {
    id: 'text-lorem-gen',
    name: 'Lorem Ipsum & Text Generator',
    description: 'Generate placeholder text paragraphs, sentences, or words for web development mockups.',
    category: 'text',
    icon: 'AlignLeft',
    tags: ['lorem', 'ipsum', 'placeholder'],
    rating: 4.8,
    usageCount: 8300,
  },
  {
    id: 'text-slug-gen',
    name: 'URL Slug Generator',
    description: 'Transform blog post titles into clean, lowercase, hyphenated URL friendly slugs.',
    category: 'text',
    icon: 'Link',
    tags: ['slug', 'url', 'seo', 'permalink'],
    rating: 4.7,
    usageCount: 5800,
  },
  {
    id: 'text-password-gen',
    name: 'Secure Password Generator',
    description: 'Generate customizable cryptographically secure passwords with numbers and symbols.',
    category: 'text',
    icon: 'Key',
    tags: ['password', 'generator', 'security'],
    rating: 4.9,
    usageCount: 14100,
    popular: true,
  },
  {
    id: 'text-qr-gen',
    name: 'Custom QR Code Creator',
    description: 'Generate scannable QR codes for websites, WiFi credentials, text, or contacts in PNG/SVG.',
    category: 'text',
    icon: 'QrCode',
    tags: ['qrcode', 'qrgenerator', 'wifi', 'brand'],
    rating: 4.9,
    usageCount: 16800,
    popular: true,
  },
  {
    id: 'text-barcode-gen',
    name: 'Barcode Generator (CODE128, EAN)',
    description: 'Create standard commercial barcodes for inventory labels and product tagging.',
    category: 'text',
    icon: 'Barcode',
    tags: ['barcode', 'code128', 'inventory'],
    rating: 4.6,
    usageCount: 4500,
  },
  {
    id: 'text-base64',
    name: 'Base64 Encoder & Decoder',
    description: 'Encode or decode strings and binary data to/from standard Base64 format.',
    category: 'text',
    icon: 'Code2',
    tags: ['base64', 'encode', 'decode'],
    rating: 4.8,
    usageCount: 7900,
  },
  {
    id: 'text-url-encode',
    name: 'URL Encoder & Decoder',
    description: 'Encode URI parameters safely for web links or parse percent-encoded URLs.',
    category: 'text',
    icon: 'Globe',
    tags: ['url', 'uri', 'encode'],
    rating: 4.7,
    usageCount: 6100,
  },
  {
    id: 'text-json-formatter',
    name: 'JSON Formatter, Validator & Tree View',
    description: 'Format, minify, validate syntax, and inspect nested JSON objects in interactive tree format.',
    category: 'text',
    icon: 'FileCode',
    tags: ['json', 'formatter', 'validator', 'minify'],
    rating: 4.9,
    usageCount: 15100,
    popular: true,
  },
  {
    id: 'text-markdown-editor',
    name: 'Live Markdown Preview Editor',
    description: 'Write Markdown with real-time formatted preview and instant HTML / TXT export.',
    category: 'text',
    icon: 'Edit3',
    tags: ['markdown', 'editor', 'preview'],
    rating: 4.8,
    usageCount: 9200,
  },

  // --- UTILITY TOOLS ---
  {
    id: 'util-age-calc',
    name: 'Exact Age Calculator',
    description: 'Calculate your exact age in years, months, days, hours, and next birthday countdown.',
    category: 'utility',
    icon: 'CalendarDays',
    tags: ['age', 'calculator', 'birthday'],
    rating: 4.9,
    usageCount: 13400,
  },
  {
    id: 'util-gst-calc',
    name: 'GST / Sales Tax Calculator',
    description: 'Calculate tax inclusive and exclusive net prices for commerce and invoicing.',
    category: 'utility',
    icon: 'Receipt',
    tags: ['gst', 'tax', 'calculator', 'sales'],
    rating: 4.8,
    usageCount: 10800,
  },
  {
    id: 'util-emi-calc',
    name: 'Loan & EMI Payment Calculator',
    description: 'Calculate monthly loan EMI installments, total interest payable, and amortization chart.',
    category: 'utility',
    icon: 'Calculator',
    tags: ['emi', 'loan', 'finance', 'interest'],
    rating: 4.9,
    usageCount: 14900,
    popular: true,
  },
  {
    id: 'util-currency-calc',
    name: 'Live Currency Converter',
    description: 'Convert real-time exchange rates across USD, EUR, INR, GBP, BDT, JPY, CAD & AUD.',
    category: 'utility',
    icon: 'DollarSign',
    tags: ['currency', 'exchange', 'forex', 'usd'],
    rating: 4.9,
    usageCount: 16100,
    popular: true,
  },
  {
    id: 'util-unit-calc',
    name: 'Multi-Unit Converter',
    description: 'Convert units for Length, Weight, Temperature, Area, Volume, Speed, and Data storage.',
    category: 'utility',
    icon: 'ArrowRightLeft',
    tags: ['unit', 'converter', 'length', 'weight'],
    rating: 4.8,
    usageCount: 11900,
  },
  {
    id: 'util-percentage-calc',
    name: 'Percentage Increase & Change Calculator',
    description: 'Solve percentage problems, discount savings, percent increase/decrease easily.',
    category: 'utility',
    icon: 'Percent',
    tags: ['percent', 'math', 'discount'],
    rating: 4.7,
    usageCount: 8700,
  },
  {
    id: 'util-sci-calc',
    name: 'Scientific Math Calculator',
    description: 'Full featured scientific calculator supporting trigonometry, logs, powers, and roots.',
    category: 'utility',
    icon: 'Binary',
    tags: ['scientific', 'calculator', 'math'],
    rating: 4.8,
    usageCount: 9600,
  },
  {
    id: 'util-timer-stopwatch',
    name: 'Precision Stopwatch & Countdown Timer',
    description: 'Track lap times with split records or set countdown timers with audio sound alerts.',
    category: 'utility',
    icon: 'Clock',
    tags: ['stopwatch', 'timer', 'clock', 'alarm'],
    rating: 4.8,
    usageCount: 10100,
  },
  {
    id: 'util-calendar-planner',
    name: 'Interactive Calendar & Event Planner',
    description: 'View monthly calendar, plan events, set task reminders, and track key dates.',
    category: 'utility',
    icon: 'Calendar',
    tags: ['calendar', 'events', 'planner', 'schedule'],
    rating: 4.7,
    usageCount: 7400,
  },
  {
    id: 'util-uuid-gen',
    name: 'UUID / GUID v4 Batch Generator',
    description: 'Generate bulk random cryptographically unique UUID v4 identifiers for databases.',
    category: 'utility',
    icon: 'Cpu',
    tags: ['uuid', 'guid', 'developer', 'id'],
    rating: 4.8,
    usageCount: 8900,
  },
  {
    id: 'util-password-strength',
    name: 'Password Strength & Entropy Analyzer',
    description: 'Test password vulnerability, estimated crack time, entropy score, and security tips.',
    category: 'utility',
    icon: 'ShieldCheck',
    tags: ['password', 'security', 'strength', 'entropy'],
    rating: 4.7,
    usageCount: 6300,
  },
  {
    id: 'util-color-picker',
    name: 'Color Picker, Palette Generator & Contrast Check',
    description: 'Pick colors, generate matching color palettes, convert HEX/RGB/HSL, and test contrast accessibility.',
    category: 'utility',
    icon: 'Palette',
    tags: ['color', 'hex', 'palette', 'picker', 'rgb'],
    rating: 4.9,
    usageCount: 12800,
    popular: true,
  },
];
