import { ToolItem } from '../types';

export const TOOLS_LIST: ToolItem[] = [
  // --- AI TOOLS ---
  {
    id: 'ai-chat',
    name: 'AI Chat Assistant',
    description: 'Smart conversational AI assistant powered by Gemini 2.5 Flash for answering questions & coding.',
    category: 'ai',
    icon: 'MessageSquare',
    tags: ['chat', 'assistant', 'gemini', 'qa'],
    isAi: true,
    rating: 4.9,
    usageCount: 14200,
    popular: true,
  },
  {
    id: 'ai-writer',
    name: 'AI Content Writer',
    description: 'Generate high quality articles, blogs, essays and long-form prose with customizable tone.',
    category: 'ai',
    icon: 'PenTool',
    tags: ['writer', 'article', 'essay', 'content'],
    isAi: true,
    rating: 4.8,
    usageCount: 9800,
    popular: true,
  },
  {
    id: 'ai-rewriter',
    name: 'AI Content Rewriter',
    description: 'Paraphrase, rephrase, and elevate existing paragraphs for clarity, flow, and tone.',
    category: 'ai',
    icon: 'RefreshCw',
    tags: ['paraphrase', 'rewrite', 'rephrase'],
    isAi: true,
    rating: 4.7,
    usageCount: 7600,
  },
  {
    id: 'ai-summarizer',
    name: 'AI Text Summarizer',
    description: 'Condense articles, reports, or documents into executive summaries and bullet points.',
    category: 'ai',
    icon: 'FileText',
    tags: ['summary', 'condense', 'tldr'],
    isAi: true,
    rating: 4.9,
    usageCount: 11200,
    popular: true,
  },
  {
    id: 'ai-translator',
    name: 'AI Multi-Language Translator',
    description: 'Translate text seamlessly across 50+ languages with contextual accuracy.',
    category: 'ai',
    icon: 'Languages',
    tags: ['translate', 'languages', 'bengali', 'hindi', 'spanish'],
    isAi: true,
    rating: 4.8,
    usageCount: 8900,
  },
  {
    id: 'ai-grammar',
    name: 'AI Grammar & Style Checker',
    description: 'Fix typos, punctuation errors, grammatical flaws, and receive stylistic suggestions.',
    category: 'ai',
    icon: 'CheckCheck',
    tags: ['grammar', 'spellcheck', 'editing'],
    isAi: true,
    rating: 4.9,
    usageCount: 13100,
    popular: true,
  },
  {
    id: 'ai-email-writer',
    name: 'AI Email Generator',
    description: 'Draft polite, formal, cold outreach, or client response emails in seconds.',
    category: 'ai',
    icon: 'Mail',
    tags: ['email', 'outreach', 'formal'],
    isAi: true,
    rating: 4.7,
    usageCount: 6500,
  },
  {
    id: 'ai-resume-builder',
    name: 'AI Resume & CV Generator',
    description: 'Create tailored ATS-friendly bullet points and summary sections for your career resume.',
    category: 'ai',
    icon: 'FileBadge',
    tags: ['resume', 'cv', 'career', 'ats'],
    isAi: true,
    isPremium: true,
    rating: 4.9,
    usageCount: 9400,
    popular: true,
  },
  {
    id: 'ai-cover-letter',
    name: 'AI Cover Letter Writer',
    description: 'Generate personalized job application pitch cover letters for targeted roles.',
    category: 'ai',
    icon: 'FileSignature',
    tags: ['coverletter', 'job', 'application'],
    isAi: true,
    rating: 4.8,
    usageCount: 5400,
  },
  {
    id: 'ai-caption-gen',
    name: 'AI Social Caption Generator',
    description: 'Create viral captions, emojis, and hashtags for Instagram, TikTok, LinkedIn, and Twitter.',
    category: 'ai',
    icon: 'Share2',
    tags: ['social', 'instagram', 'hashtags', 'caption'],
    isAi: true,
    rating: 4.7,
    usageCount: 8100,
  },
  {
    id: 'ai-prompt-gen',
    name: 'AI Prompt Builder',
    description: 'Engineered prompts for Midjourney, DALL-E 3, ChatGPT, and Stable Diffusion.',
    category: 'ai',
    icon: 'Zap',
    tags: ['prompt', 'midjourney', 'dalle'],
    isAi: true,
    rating: 4.8,
    usageCount: 7200,
  },
  {
    id: 'ai-blog-writer',
    name: 'AI Full Blog Post Generator',
    description: 'Generate complete SEO-optimized blog posts with headings, outline, and conclusion.',
    category: 'ai',
    icon: 'Newspaper',
    tags: ['blog', 'seo', 'article'],
    isAi: true,
    isPremium: true,
    rating: 4.9,
    usageCount: 10500,
  },
  {
    id: 'ai-story-writer',
    name: 'AI Fiction & Story Creator',
    description: 'Craft engaging creative stories, sci-fi, drama, or fantasy narratives with custom genres.',
    category: 'ai',
    icon: 'BookOpen',
    tags: ['story', 'fiction', 'novel'],
    isAi: true,
    rating: 4.6,
    usageCount: 4300,
  },
  {
    id: 'ai-script-writer',
    name: 'AI Video Script Writer',
    description: 'Generate structured video scripts with visual cues for YouTube, Shorts, and Reels.',
    category: 'ai',
    icon: 'Video',
    tags: ['script', 'youtube', 'reels', 'tiktok'],
    isAi: true,
    rating: 4.8,
    usageCount: 6100,
  },
  {
    id: 'ai-code-gen',
    name: 'AI Code Generator',
    description: 'Generate clean React, TypeScript, Python, SQL, C++, Java or HTML/CSS code.',
    category: 'ai',
    icon: 'Code',
    tags: ['code', 'python', 'react', 'typescript'],
    isAi: true,
    rating: 4.9,
    usageCount: 15600,
    popular: true,
  },
  {
    id: 'ai-debugger',
    name: 'AI Code Debugger',
    description: 'Paste error stack traces or buggy code snippets to receive immediate fixes.',
    category: 'ai',
    icon: 'Bug',
    tags: ['debug', 'error', 'fix', 'code'],
    isAi: true,
    rating: 4.8,
    usageCount: 8400,
  },
  {
    id: 'ai-sql-gen',
    name: 'AI Natural Language to SQL',
    description: 'Convert English queries into production-ready SQL statements for Postgres, MySQL & SQLite.',
    category: 'ai',
    icon: 'Database',
    tags: ['sql', 'database', 'postgres', 'mysql'],
    isAi: true,
    rating: 4.7,
    usageCount: 5200,
  },
  {
    id: 'ai-regex-gen',
    name: 'AI Regex Generator & Explainer',
    description: 'Construct regular expressions from plain text descriptions with syntax breakdown.',
    category: 'ai',
    icon: 'Binary',
    tags: ['regex', 'pattern', 'text'],
    isAi: true,
    rating: 4.8,
    usageCount: 4900,
  },
  {
    id: 'ai-ocr',
    name: 'AI Vision OCR (Image to Text)',
    description: 'Upload images, receipts, or document photos to extract structured text using Gemini AI Vision.',
    category: 'ai',
    icon: 'Eye',
    tags: ['ocr', 'image-text', 'vision', 'scan'],
    isAi: true,
    isPremium: true,
    rating: 4.9,
    usageCount: 11800,
    popular: true,
  },
  {
    id: 'ai-speech-to-text',
    name: 'AI Voice to Text Transcriber',
    description: 'Speak into your microphone or upload speech to get high-accuracy text transcriptions.',
    category: 'ai',
    icon: 'Mic',
    tags: ['voice', 'speech', 'audio', 'transcribe'],
    isAi: true,
    rating: 4.7,
    usageCount: 6800,
  },
  {
    id: 'ai-text-to-speech',
    name: 'AI Text to Speech Reader',
    description: 'Convert written text into natural-sounding voice audio with adjustable speed & pitch.',
    category: 'ai',
    icon: 'Volume2',
    tags: ['tts', 'voice', 'audio', 'speech'],
    isAi: true,
    rating: 4.8,
    usageCount: 7900,
  },
  {
    id: 'ai-image-desc',
    name: 'AI Image Analyzer & Tag Generator',
    description: 'Get detailed visual descriptions, accessibility alt text, and meta tags for images.',
    category: 'ai',
    icon: 'Image',
    tags: ['image', 'vision', 'alttext', 'analysis'],
    isAi: true,
    rating: 4.6,
    usageCount: 4100,
  },
  {
    id: 'ai-pdf-chat',
    name: 'AI PDF Document Q&A',
    description: 'Upload PDF content or paste documents to ask questions, extract facts & study notes.',
    category: 'ai',
    icon: 'FileQuestion',
    tags: ['pdf', 'chatpdf', 'qna', 'document'],
    isAi: true,
    isPremium: true,
    rating: 4.9,
    usageCount: 16200,
    popular: true,
  },

  // --- PDF TOOLS (33 COMPLETE TOOLS) ---
  // ORGANIZE PDF
  {
    id: 'pdf-merge',
    name: 'Merge PDF Documents',
    description: 'Combine multiple PDF files into one single organized PDF file.',
    category: 'pdf',
    icon: 'FilePlus',
    tags: ['pdf', 'merge', 'combine', 'organize'],
    rating: 4.9,
    usageCount: 18400,
    popular: true,
  },
  {
    id: 'pdf-split',
    name: 'Split PDF Pages',
    description: 'Divide a large PDF into separate files or custom page ranges.',
    category: 'pdf',
    icon: 'Scissors',
    tags: ['pdf', 'split', 'cut', 'pages', 'organize'],
    rating: 4.8,
    usageCount: 12100,
    popular: true,
  },
  {
    id: 'pdf-remove-pages',
    name: 'Remove PDF Pages',
    description: 'Delete specific unwanted pages from your PDF document.',
    category: 'pdf',
    icon: 'Trash2',
    tags: ['pdf', 'remove', 'delete', 'pages'],
    rating: 4.8,
    usageCount: 9400,
  },
  {
    id: 'pdf-extract-pages',
    name: 'Extract PDF Pages',
    description: 'Select and save specific page numbers from a document into a new PDF.',
    category: 'pdf',
    icon: 'Layers',
    tags: ['pdf', 'pages', 'extract'],
    rating: 4.8,
    usageCount: 7300,
  },
  {
    id: 'pdf-organize',
    name: 'Organize & Reorder PDF',
    description: 'Drag, reorder, sort, or rotate individual PDF pages visually.',
    category: 'pdf',
    icon: 'ArrowUpDown',
    tags: ['pdf', 'organize', 'reorder', 'sort'],
    rating: 4.9,
    usageCount: 11500,
    popular: true,
  },
  {
    id: 'pdf-scan',
    name: 'Scan to PDF',
    description: 'Capture document photos or camera video stream to generate a clean PDF.',
    category: 'pdf',
    icon: 'Camera',
    tags: ['pdf', 'scan', 'camera', 'photo'],
    rating: 4.7,
    usageCount: 8200,
  },

  // OPTIMIZE PDF
  {
    id: 'pdf-compress',
    name: 'Compress PDF Size',
    description: 'Reduce PDF file size significantly while keeping crisp visual quality.',
    category: 'pdf',
    icon: 'FileArchive',
    tags: ['pdf', 'compress', 'reduce', 'optimize'],
    rating: 4.9,
    usageCount: 15300,
    popular: true,
  },
  {
    id: 'pdf-repair',
    name: 'Repair & Fix PDF',
    description: 'Fix damaged, corrupted, or unreadable PDF document headers and structures.',
    category: 'pdf',
    icon: 'Wrench',
    tags: ['pdf', 'repair', 'fix', 'corrupt'],
    rating: 4.7,
    usageCount: 6100,
  },
  {
    id: 'pdf-ocr',
    name: 'OCR PDF (Searchable PDF)',
    description: 'Extract and recognize text from scanned image PDFs using AI Vision.',
    category: 'pdf',
    icon: 'Eye',
    tags: ['pdf', 'ocr', 'text-recognition', 'scan'],
    isAi: true,
    rating: 4.9,
    usageCount: 13900,
    popular: true,
  },

  // CONVERT TO PDF
  {
    id: 'pdf-image-to-pdf',
    name: 'JPG / Images to PDF',
    description: 'Convert JPG, PNG, WEBP, or GIF photos into a single PDF document.',
    category: 'pdf',
    icon: 'ImagePlus',
    tags: ['pdf', 'jpg-pdf', 'images', 'png'],
    rating: 4.9,
    usageCount: 14700,
    popular: true,
  },
  {
    id: 'pdf-word-to-pdf',
    name: 'WORD to PDF Converter',
    description: 'Convert DOCX, DOC, or rich Word text documents into PDF.',
    category: 'pdf',
    icon: 'FileType',
    tags: ['pdf', 'word', 'docx', 'convert'],
    rating: 4.8,
    usageCount: 16200,
    popular: true,
  },
  {
    id: 'pdf-ppt-to-pdf',
    name: 'POWERPOINT to PDF',
    description: 'Convert PowerPoint slide presentations into clean PDF documents.',
    category: 'pdf',
    icon: 'Presentation',
    tags: ['pdf', 'powerpoint', 'ppt', 'slides'],
    rating: 4.7,
    usageCount: 9800,
  },
  {
    id: 'pdf-excel-to-pdf',
    name: 'EXCEL to PDF Converter',
    description: 'Convert Excel spreadsheets (XLSX, CSV) into clean PDF tables.',
    category: 'pdf',
    icon: 'Table',
    tags: ['pdf', 'excel', 'xlsx', 'csv'],
    rating: 4.7,
    usageCount: 8400,
  },
  {
    id: 'pdf-html-to-pdf',
    name: 'HTML & Web to PDF',
    description: 'Convert raw HTML code, web pages, or online markup directly to PDF.',
    category: 'pdf',
    icon: 'Code',
    tags: ['pdf', 'html', 'web', 'convert'],
    rating: 4.6,
    usageCount: 5900,
  },

  // CONVERT FROM PDF
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG Images',
    description: 'Extract every page of your PDF as high-resolution JPG image files.',
    category: 'pdf',
    icon: 'Image',
    tags: ['pdf', 'pdf-jpg', 'extract', 'images'],
    rating: 4.9,
    usageCount: 17100,
    popular: true,
  },
  {
    id: 'pdf-to-word',
    name: 'PDF to WORD Converter',
    description: 'Convert PDF document pages into editable Word document text.',
    category: 'pdf',
    icon: 'FileText',
    tags: ['pdf', 'pdf-word', 'docx', 'editable'],
    rating: 4.8,
    usageCount: 18900,
    popular: true,
  },
  {
    id: 'pdf-to-ppt',
    name: 'PDF to POWERPOINT',
    description: 'Convert PDF document pages into PowerPoint presentation slides.',
    category: 'pdf',
    icon: 'Presentation',
    tags: ['pdf', 'pdf-ppt', 'slides'],
    rating: 4.7,
    usageCount: 8100,
  },
  {
    id: 'pdf-to-excel',
    name: 'PDF to EXCEL Data',
    description: 'Extract tables and spreadsheet data from PDF into CSV/Excel format.',
    category: 'pdf',
    icon: 'Sheet',
    tags: ['pdf', 'pdf-excel', 'csv', 'tables'],
    rating: 4.7,
    usageCount: 9200,
  },
  {
    id: 'pdf-to-pdfa',
    name: 'PDF to PDF/A (Archival)',
    description: 'Standardize PDF files for ISO-compliant long-term document archiving.',
    category: 'pdf',
    icon: 'FileCheck',
    tags: ['pdf', 'pdfa', 'archive', 'iso'],
    rating: 4.6,
    usageCount: 4100,
  },

  // EDIT PDF
  {
    id: 'pdf-rotate',
    name: 'Rotate PDF Pages',
    description: 'Rotate PDF pages 90, 180, or 270 degrees clockwise or counterclockwise.',
    category: 'pdf',
    icon: 'RotateCw',
    tags: ['pdf', 'rotate', 'orient'],
    rating: 4.8,
    usageCount: 5900,
  },
  {
    id: 'pdf-page-number',
    name: 'Add Page Numbers',
    description: 'Insert customizable page numbering at the top or bottom of PDF pages.',
    category: 'pdf',
    icon: 'Binary',
    tags: ['pdf', 'page-numbers', 'footer', 'header'],
    rating: 4.8,
    usageCount: 7800,
  },
  {
    id: 'pdf-watermark',
    name: 'Add PDF Watermark',
    description: 'Overlay custom text watermarks, stamp logos, or dates onto PDF pages.',
    category: 'pdf',
    icon: 'Stamp',
    tags: ['pdf', 'watermark', 'protect'],
    rating: 4.7,
    usageCount: 6200,
  },
  {
    id: 'pdf-crop',
    name: 'Crop PDF Margins',
    description: 'Trim page margins and adjust visible canvas bounding boxes.',
    category: 'pdf',
    icon: 'Crop',
    tags: ['pdf', 'crop', 'margin', 'trim'],
    rating: 4.7,
    usageCount: 6500,
  },
  {
    id: 'pdf-edit',
    name: 'Edit PDF & Annotate',
    description: 'Draw, write text notes, add highlights, or insert shapes onto PDF pages.',
    category: 'pdf',
    icon: 'Edit3',
    tags: ['pdf', 'edit', 'annotate', 'draw'],
    rating: 4.8,
    usageCount: 11400,
    popular: true,
  },
  {
    id: 'pdf-forms',
    name: 'PDF Forms Filler',
    description: 'Fill out interactive form fields or add fillable inputs and checkboxes.',
    category: 'pdf',
    icon: 'CheckSquare',
    tags: ['pdf', 'forms', 'fill', 'checkbox'],
    rating: 4.7,
    usageCount: 5800,
  },

  // PDF SECURITY
  {
    id: 'pdf-unlock',
    name: 'Unlock PDF Password',
    description: 'Remove password restrictions and owner locks from PDF files.',
    category: 'pdf',
    icon: 'Unlock',
    tags: ['pdf', 'unlock', 'password', 'decrypt'],
    rating: 4.8,
    usageCount: 12800,
    popular: true,
  },
  {
    id: 'pdf-protect',
    name: 'Protect PDF with Password',
    description: 'Encrypt PDF files with strong custom user passwords and permissions.',
    category: 'pdf',
    icon: 'Lock',
    tags: ['pdf', 'protect', 'password', 'encrypt'],
    rating: 4.8,
    usageCount: 10600,
  },
  {
    id: 'pdf-sign',
    name: 'Sign PDF Document',
    description: 'Draw digital signatures, type signatures, or insert signature stamps onto PDF.',
    category: 'pdf',
    icon: 'PenTool',
    tags: ['pdf', 'sign', 'signature', 'e-sign'],
    rating: 4.9,
    usageCount: 15100,
    popular: true,
  },
  {
    id: 'pdf-redact',
    name: 'Redact & Censor PDF',
    description: 'Permanently black out sensitive numbers, names, or private content on PDF.',
    category: 'pdf',
    icon: 'EyeOff',
    tags: ['pdf', 'redact', 'censor', 'blackout'],
    rating: 4.8,
    usageCount: 8700,
  },
  {
    id: 'pdf-compare',
    name: 'Compare PDF Documents',
    description: 'Compare two PDF files side-by-side to detect text or visual differences.',
    category: 'pdf',
    icon: 'GitCompare',
    tags: ['pdf', 'compare', 'diff', 'diff-check'],
    rating: 4.7,
    usageCount: 5400,
  },

  // PDF INTELLIGENCE
  {
    id: 'pdf-ai-summarizer',
    name: 'AI PDF Summarizer',
    description: 'Summarize entire PDF documents into executive highlights using Gemini AI.',
    category: 'pdf',
    icon: 'Sparkles',
    tags: ['pdf', 'ai', 'summarize', 'tldr'],
    isAi: true,
    rating: 4.9,
    usageCount: 16800,
    popular: true,
  },
  {
    id: 'pdf-ai-translate',
    name: 'Translate PDF Document',
    description: 'Translate PDF document text into 50+ foreign languages accurately.',
    category: 'pdf',
    icon: 'Languages',
    tags: ['pdf', 'ai', 'translate', 'languages'],
    isAi: true,
    rating: 4.8,
    usageCount: 11200,
  },
  {
    id: 'pdf-to-markdown',
    name: 'PDF to Markdown',
    description: 'Convert PDF formatting and headings into Markdown for Notion & Obsidian.',
    category: 'pdf',
    icon: 'FileCode',
    tags: ['pdf', 'markdown', 'notion', 'obsidian'],
    rating: 4.7,
    usageCount: 7100,
  },

  // --- IMAGE TOOLS ---
  {
    id: 'img-bg-remover',
    name: 'AI Background Mask & Eraser',
    description: 'Remove background colors and isolate subject elements using canvas masking.',
    category: 'image',
    icon: 'Eraser',
    tags: ['bgremover', 'background', 'transparent', 'png'],
    rating: 4.9,
    usageCount: 19800,
    popular: true,
  },
  {
    id: 'img-compressor',
    name: 'Image Compressor & Optimizer',
    description: 'Compress PNG, JPG, or WEBP image file sizes with real-time quality slider preview.',
    category: 'image',
    icon: 'Minimize2',
    tags: ['compress', 'optimize', 'png', 'jpg'],
    rating: 4.9,
    usageCount: 16500,
    popular: true,
  },
  {
    id: 'img-resizer',
    name: 'Image Resizer & Scaler',
    description: 'Resize image dimensions by pixels or percentage with aspect ratio lock.',
    category: 'image',
    icon: 'Scaling',
    tags: ['resize', 'dimensions', 'width', 'height'],
    rating: 4.8,
    usageCount: 11200,
  },
  {
    id: 'img-cropper',
    name: 'Interactive Image Crop Tool',
    description: 'Crop images to exact aspect ratios like 1:1 square, 16:9 landscape, 9:16 story, or custom.',
    category: 'image',
    icon: 'Crop',
    tags: ['crop', 'aspect', 'square'],
    rating: 4.8,
    usageCount: 9400,
  },
  {
    id: 'img-converter',
    name: 'Universal Image Format Converter',
    description: 'Convert images instantly between JPG, PNG, WEBP, GIF, AVIF, SVG, RAW, TIFF, PSD, AI, EPS, PDF, and BMP formats.',
    category: 'image',
    icon: 'RefreshCcw',
    tags: ['convert', 'jpg', 'jpeg', 'png', 'webp', 'gif', 'avif', 'svg', 'raw', 'tiff', 'psd', 'ai', 'eps', 'pdf', 'bmp'],
    rating: 4.9,
    usageCount: 19400,
    popular: true,
  },
  {
    id: 'img-enhancer',
    name: 'Image Filter & Photo Enhancer',
    description: 'Adjust brightness, contrast, saturation, sharpness, warm tones, and vintage filters.',
    category: 'image',
    icon: 'Sliders',
    tags: ['enhance', 'filter', 'photo', 'adjust'],
    rating: 4.7,
    usageCount: 8200,
  },
  {
    id: 'img-blur',
    name: 'Background Blur Tool',
    description: 'Apply soft gaussian radial blur effects or privacy blurs to sensitive areas.',
    category: 'image',
    icon: 'Aperture',
    tags: ['blur', 'portrait', 'privacy'],
    rating: 4.6,
    usageCount: 5100,
  },
  {
    id: 'img-watermark-remover',
    name: 'Spot Touch-up & Spot Eraser',
    description: 'Interactive canvas brush tool to clone and touch up unwanted artifacts or spots.',
    category: 'image',
    icon: 'Paintbrush',
    tags: ['touchup', 'eraser', 'spot', 'clean'],
    rating: 4.7,
    usageCount: 7100,
  },
  {
    id: 'img-qr-scanner',
    name: 'QR Code & Barcode Image Scanner',
    description: 'Upload image files or use web camera to decode embedded QR links and barcodes.',
    category: 'image',
    icon: 'QrCode',
    tags: ['qr', 'scanner', 'barcode', 'decode'],
    rating: 4.8,
    usageCount: 9900,
  },
  {
    id: 'img-qr-creator',
    name: 'Custom QR Code Creator & Designer',
    description: 'Generate high quality customized QR codes with custom colors, gradients, center logo overlays, dot styles, eye frames, and multi-format templates (WiFi, vCard, UPI, URL, WhatsApp).',
    category: 'image',
    icon: 'QrCode',
    tags: ['qr', 'generator', 'creator', 'designer', 'custom', 'branding', 'wifi', 'vcard', 'upi', 'logo'],
    rating: 4.9,
    usageCount: 18700,
    popular: true,
  },

  // --- TEXT TOOLS ---
  {
    id: 'text-online-notepad',
    name: 'Online Notepad & Text Editor',
    description: 'Fast, distraction-free online notepad with rich formatting, auto-save, markdown preview, AI writing assistant, and multi-note management.',
    category: 'text',
    icon: 'FileText',
    tags: ['notepad', 'notes', 'editor', 'text', 'markdown', 'write', 'scratchpad'],
    rating: 5.0,
    usageCount: 28400,
    popular: true,
  },
  {
    id: 'text-word-counter',
    name: 'Word, Character & Sentence Counter',
    description: 'Analyze word count, character count, reading time, speaking duration, and sentence structure.',
    category: 'text',
    icon: 'Hash',
    tags: ['words', 'counter', 'characters', 'stats'],
    rating: 4.9,
    usageCount: 17200,
    popular: true,
  },
  {
    id: 'text-case-converter',
    name: 'Case Converter Tool',
    description: 'Convert text instantly to UPPERCASE, lowercase, Title Case, Sentence case, camelCase, kebab-case & snake_case.',
    category: 'text',
    icon: 'Type',
    tags: ['case', 'uppercase', 'lowercase', 'camelcase'],
    rating: 4.8,
    usageCount: 10400,
  },
  {
    id: 'text-sort-text',
    name: 'Sort Text',
    description: 'Sort a list in alphabetical, natural, reverse, or random order.',
    category: 'text',
    icon: 'ArrowUpDown',
    tags: ['sort', 'alphabetical', 'order', 'list'],
    rating: 4.8,
    usageCount: 8900,
  },
  {
    id: 'text-find-replace',
    name: 'Find & Replace',
    description: 'Find all instances the text appears in a document and replace it with another word.',
    category: 'text',
    icon: 'Search',
    tags: ['find', 'replace', 'search', 'substitute'],
    rating: 4.9,
    usageCount: 12300,
    popular: true,
  },
  {
    id: 'text-reverse-list',
    name: 'Reverse List',
    description: 'Flip a list vertically to transform a list in reverse order.',
    category: 'text',
    icon: 'ArrowDownUp',
    tags: ['reverse', 'flip', 'list', 'invert'],
    rating: 4.7,
    usageCount: 5400,
  },
  {
    id: 'text-diff-checker',
    name: 'Difference Checker',
    description: 'Compare text files and find the differences side-by-side.',
    category: 'text',
    icon: 'FileDiff',
    tags: ['diff', 'compare', 'difference', 'checker'],
    rating: 4.9,
    usageCount: 11200,
    popular: true,
  },
  {
    id: 'text-prefix-suffix',
    name: 'Add Prefix & Suffix',
    description: 'Place any characters at the beginning and/or end of each line.',
    category: 'text',
    icon: 'PlusCircle',
    tags: ['prefix', 'suffix', 'prepend', 'append'],
    rating: 4.8,
    usageCount: 7100,
  },
  {
    id: 'text-add-line-breaks',
    name: 'Add Line Breaks',
    description: 'Split a block of text into multiple lines by adding line breaks after characters or words.',
    category: 'text',
    icon: 'CornerDownLeft',
    tags: ['linebreaks', 'split', 'wrap', 'format'],
    rating: 4.6,
    usageCount: 4900,
  },
  {
    id: 'text-remove-line-breaks',
    name: 'Remove Line Breaks',
    description: 'Remove all line breaks in a text or replace them with spaces or custom characters.',
    category: 'text',
    icon: 'Minimize2',
    tags: ['unwrap', 'removebreaks', 'singleline'],
    rating: 4.8,
    usageCount: 9400,
  },
  {
    id: 'text-concatenate',
    name: 'Concatenate Text',
    description: 'Combine and merge two documents by concatenating texts line by line.',
    category: 'text',
    icon: 'Combine',
    tags: ['combine', 'merge', 'concatenate', 'join'],
    rating: 4.7,
    usageCount: 6200,
  },
  {
    id: 'text-split-text',
    name: 'Split Text',
    description: 'Specify the delimiter and split text into individual columns or lines.',
    category: 'text',
    icon: 'Scissors',
    tags: ['split', 'delimiter', 'columns', 'separate'],
    rating: 4.8,
    usageCount: 7800,
  },
  {
    id: 'text-extract-column',
    name: 'Extract Column',
    description: 'Split delimited text and grab a specific column number.',
    category: 'text',
    icon: 'Columns',
    tags: ['column', 'extract', 'csv', 'tsv'],
    rating: 4.7,
    usageCount: 5900,
  },
  {
    id: 'text-swap-columns',
    name: 'Swap Columns',
    description: 'Swap two columns from a delimited text document.',
    category: 'text',
    icon: 'ArrowRightLeft',
    tags: ['swap', 'columns', 'csv', 'reorder'],
    rating: 4.6,
    usageCount: 4200,
  },
  {
    id: 'text-reverse-words',
    name: 'Reverse Words',
    description: 'Reverse the order of words in a text block.',
    category: 'text',
    icon: 'Repeat',
    tags: ['reverse', 'words', 'flip'],
    rating: 4.6,
    usageCount: 4100,
  },
  {
    id: 'text-reverse-letters',
    name: 'Reverse Letters',
    description: 'Reverse the order of all characters and letters in a text.',
    category: 'text',
    icon: 'FlipHorizontal',
    tags: ['reverse', 'letters', 'characters'],
    rating: 4.6,
    usageCount: 3900,
  },
  {
    id: 'text-remove-extra-spaces',
    name: 'Remove Extra Spaces',
    description: 'Trim leading/trailing spaces and convert multiple spaces into a single space.',
    category: 'text',
    icon: 'Eraser',
    tags: ['trim', 'spaces', 'clean', 'whitespace'],
    rating: 4.8,
    usageCount: 8700,
  },
  {
    id: 'text-duplicate-remover',
    name: 'Remove Duplicate Lines',
    description: 'Find identical lines in a document and delete duplicates to clean up your text.',
    category: 'text',
    icon: 'ListFilter',
    tags: ['duplicates', 'cleaner', 'dedupe'],
    rating: 4.7,
    usageCount: 6700,
  },
  {
    id: 'text-remove-empty-lines',
    name: 'Remove Empty Lines',
    description: 'Get rid of all lines in a text that only consist of spaces or tabs.',
    category: 'text',
    icon: 'ListX',
    tags: ['emptylines', 'clean', 'deleteblank'],
    rating: 4.8,
    usageCount: 9100,
  },
  {
    id: 'text-remove-accents',
    name: 'Remove Letter Accents',
    description: 'Remove accents or diacritics to transform accented letters into Latin characters.',
    category: 'text',
    icon: 'Type',
    tags: ['accents', 'diacritics', 'normalize', 'latin'],
    rating: 4.7,
    usageCount: 5200,
  },
  {
    id: 'text-remove-unwanted-chars',
    name: 'Remove Unwanted Characters',
    description: 'Delete specific unwanted characters or strip all non-alphanumeric characters.',
    category: 'text',
    icon: 'FilterX',
    tags: ['strip', 'sanitize', 'clean', 'alphanumeric'],
    rating: 4.7,
    usageCount: 6400,
  },
  {
    id: 'text-remove-lines-containing',
    name: 'Remove Lines Containing',
    description: 'Remove lines containing or not containing a specific word, phrase, or string.',
    category: 'text',
    icon: 'Filter',
    tags: ['filter', 'removelines', 'keyword', 'grep'],
    rating: 4.8,
    usageCount: 7300,
  },
  {
    id: 'text-remove-emojis',
    name: 'Remove Emojis',
    description: 'Remove all emojis and Unicode symbols embedded in plain text messages.',
    category: 'text',
    icon: 'SmileOff',
    tags: ['emojis', 'strip', 'clean', 'symbols'],
    rating: 4.7,
    usageCount: 5600,
  },
  {
    id: 'text-strip-html',
    name: 'Strip HTML Tags',
    description: 'Strips out all HTML tags from text or markdown.',
    category: 'text',
    icon: 'Code',
    tags: ['html', 'strip', 'tags', 'clean'],
    rating: 4.8,
    usageCount: 8300,
  },
  {
    id: 'text-add-line-numbers',
    name: 'Add Line Numbers',
    description: 'Add sequential numbers, letters, or roman numerals at the beginning of each line.',
    category: 'text',
    icon: 'ListOrdered',
    tags: ['linenumbers', 'numbering', 'index'],
    rating: 4.7,
    usageCount: 6800,
  },
  {
    id: 'text-add-commas-numbers',
    name: 'Add Commas to Numbers',
    description: 'Add commas or periods to unformatted numbers in a text.',
    category: 'text',
    icon: 'DollarSign',
    tags: ['commas', 'currency', 'numbers', 'format'],
    rating: 4.7,
    usageCount: 5100,
  },
  {
    id: 'text-replace-quotes',
    name: 'Replace Smart/Straight Quotes',
    description: 'Replace curly/smart quotes with regular straight quotes and vice versa.',
    category: 'text',
    icon: 'Quote',
    tags: ['quotes', 'smartquotes', 'curly', 'straight'],
    rating: 4.6,
    usageCount: 4300,
  },
  {
    id: 'text-tabs-to-spaces',
    name: 'Tabs to Spaces',
    description: 'Take up less whitespace by converting tab characters to spaces.',
    category: 'text',
    icon: 'Space',
    tags: ['tabs', 'spaces', 'indent', 'format'],
    rating: 4.7,
    usageCount: 4900,
  },
  {
    id: 'text-spaces-to-tabs',
    name: 'Spaces to Tabs',
    description: 'Convert spaces to tabs for formatting purposes.',
    category: 'text',
    icon: 'Space',
    tags: ['spaces', 'tabs', 'indent', 'format'],
    rating: 4.6,
    usageCount: 3800,
  },
  {
    id: 'text-pad-text',
    name: 'Pad Text',
    description: 'Pad text to the left or right with spaces or any character.',
    category: 'text',
    icon: 'Maximize2',
    tags: ['pad', 'padding', 'align', 'width'],
    rating: 4.6,
    usageCount: 3500,
  },
  {
    id: 'text-word-wrap',
    name: 'Word Wrap',
    description: 'Wrap text based on specified character length per line.',
    category: 'text',
    icon: 'WrapText',
    tags: ['wrap', 'linebreaks', 'width'],
    rating: 4.7,
    usageCount: 5100,
  },
  {
    id: 'text-justify-text',
    name: 'Justify Text',
    description: 'Wraps words to a specified length and justifies the text in each line.',
    category: 'text',
    icon: 'AlignJustify',
    tags: ['justify', 'align', 'text'],
    rating: 4.6,
    usageCount: 3700,
  },
  {
    id: 'text-center-text',
    name: 'Center Text',
    description: 'Center text horizontally by equally padding left and right with spaces.',
    category: 'text',
    icon: 'AlignCenter',
    tags: ['center', 'align', 'pad'],
    rating: 4.6,
    usageCount: 3900,
  },
  {
    id: 'text-upside-down',
    name: 'Upside Down Text Generator',
    description: 'Flip text, letters, and words! Turn text upside down.',
    category: 'text',
    icon: 'RotateCw',
    tags: ['upsidedown', 'flip', 'fancy', 'unicode'],
    rating: 4.8,
    usageCount: 9700,
  },
  {
    id: 'text-unicode-bold',
    name: 'Bold Text Generator',
    description: 'Convert normal text into bold text using raw Unicode characters.',
    category: 'text',
    icon: 'Bold',
    tags: ['bold', 'fancy', 'unicode', 'font'],
    rating: 4.9,
    usageCount: 13500,
    popular: true,
  },
  {
    id: 'text-unicode-italic',
    name: 'Italic Text Generator',
    description: 'Turn normal text into italics using raw Unicode characters.',
    category: 'text',
    icon: 'Italic',
    tags: ['italic', 'fancy', 'unicode', 'font'],
    rating: 4.8,
    usageCount: 10200,
  },
  {
    id: 'text-unicode-old-english',
    name: 'Old English Text Generator',
    description: 'Convert simple text into old English blackletter script.',
    category: 'text',
    icon: 'Sparkles',
    tags: ['oldenglish', 'gothic', 'blackletter', 'unicode'],
    rating: 4.8,
    usageCount: 8800,
  },
  {
    id: 'text-unicode-cursive',
    name: 'Cursive Text Generator',
    description: 'Convert simple normal text into fancy cursive using Unicode characters.',
    category: 'text',
    icon: 'Feather',
    tags: ['cursive', 'fancy', 'script', 'handwriting'],
    rating: 4.9,
    usageCount: 11900,
    popular: true,
  },
  {
    id: 'text-normalize-unicode',
    name: 'Normalize Unicode Text',
    description: 'Revert bold, italicized, and fancy Unicode text back to regular normal text.',
    category: 'text',
    icon: 'Sparkles',
    tags: ['normalize', 'unfancy', 'plain', 'unicode'],
    rating: 4.7,
    usageCount: 4600,
  },
  {
    id: 'text-html-encode-decode',
    name: 'HTML Encode/Decode',
    description: 'Convert characters and symbols into HTML entities and vice-versa.',
    category: 'text',
    icon: 'Code2',
    tags: ['html', 'entities', 'encode', 'decode'],
    rating: 4.8,
    usageCount: 7600,
  },
  {
    id: 'text-url-encode',
    name: 'URL Encoder & Decoder',
    description: 'Encode URI parameters safely for web links or parse percent-encoded URLs.',
    category: 'text',
    icon: 'Globe',
    tags: ['url', 'uri', 'encode'],
    rating: 4.7,
    usageCount: 6100,
  },
  {
    id: 'text-html-escape',
    name: 'HTML Escape/Unescape',
    description: 'Convert plain unescaped HTML code into escaped HTML and vice-versa.',
    category: 'text',
    icon: 'Code',
    tags: ['escape', 'unescape', 'html'],
    rating: 4.7,
    usageCount: 6100,
  },
  {
    id: 'text-username-gen',
    name: 'Username Generator',
    description: 'Find yourself a unique username that you can use on any social media site.',
    category: 'text',
    icon: 'User',
    tags: ['username', 'handle', 'gaming', 'social'],
    rating: 4.8,
    usageCount: 9900,
  },
  {
    id: 'text-password-gen',
    name: 'Strong Password Generator',
    description: 'Generate a strong, secure, and valid password that no one can guess.',
    category: 'text',
    icon: 'Key',
    tags: ['password', 'generator', 'security'],
    rating: 4.9,
    usageCount: 14100,
    popular: true,
  },
  {
    id: 'text-pronounceable-pass',
    name: 'Pronounceable Password',
    description: 'Get yourself a pronounceable password that is both secure and easy to remember.',
    category: 'text',
    icon: 'Key',
    tags: ['pronounceable', 'password', 'readable', 'security'],
    rating: 4.8,
    usageCount: 8200,
  },
  {
    id: 'text-random-string',
    name: 'Random String Generator',
    description: 'Generate a random string based on your defined length and character set.',
    category: 'text',
    icon: 'Hash',
    tags: ['random', 'string', 'generator', 'token'],
    rating: 4.7,
    usageCount: 6500,
  },
  {
    id: 'text-random-words',
    name: 'Random Word Generator',
    description: 'Generate single or multiple random words based on your defined word length.',
    category: 'text',
    icon: 'Type',
    tags: ['random', 'words', 'generator', 'vocab'],
    rating: 4.8,
    usageCount: 7400,
  },
  {
    id: 'text-lorem-gen',
    name: 'Filler Text (Lorem Ipsum)',
    description: 'Generate placeholder/dummy text for your mockup design.',
    category: 'text',
    icon: 'AlignLeft',
    tags: ['lorem', 'ipsum', 'placeholder'],
    rating: 4.8,
    usageCount: 8300,
  },
  {
    id: 'text-random-numbers',
    name: 'Random Number Generator',
    description: 'Generate one or more numbers randomly from a defined range of numbers.',
    category: 'text',
    icon: 'Shuffle',
    tags: ['random', 'numbers', 'range', 'generator'],
    rating: 4.9,
    usageCount: 11500,
    popular: true,
  },
  {
    id: 'text-random-emails',
    name: 'Random Email Generator',
    description: 'Create unregistered email addresses in bulk using random names and characters.',
    category: 'text',
    icon: 'Mail',
    tags: ['email', 'random', 'test', 'dummy'],
    rating: 4.7,
    usageCount: 8100,
  },
  {
    id: 'text-email-extractor',
    name: 'Email Extractor',
    description: 'Automatically extract or scrape all email addresses from unstructured data.',
    category: 'text',
    icon: 'Mail',
    tags: ['email', 'extractor', 'scrape', 'regex'],
    rating: 4.9,
    usageCount: 12900,
    popular: true,
  },
  {
    id: 'text-url-extractor',
    name: 'URL Extractor',
    description: 'Automatically extract or scrape all URLs from an unstructured text.',
    category: 'text',
    icon: 'Link',
    tags: ['url', 'extractor', 'links', 'scrape'],
    rating: 4.8,
    usageCount: 10600,
  },
  {
    id: 'text-slug-gen',
    name: 'URL Slug Generator',
    description: 'Transform blog post titles into clean, lowercase, hyphenated URL friendly slugs.',
    category: 'text',
    icon: 'Link',
    tags: ['slug', 'url', 'seo', 'permalink'],
    rating: 4.7,
    usageCount: 5800,
  },
  {
    id: 'text-qr-gen',
    name: 'Custom QR Code Creator',
    description: 'Generate scannable QR codes for websites, WiFi credentials, text, or contacts in PNG/SVG.',
    category: 'text',
    icon: 'QrCode',
    tags: ['qrcode', 'qrgenerator', 'wifi', 'brand'],
    rating: 4.9,
    usageCount: 16800,
    popular: true,
  },
  {
    id: 'text-barcode-gen',
    name: 'Barcode Generator (CODE128, EAN)',
    description: 'Create standard commercial barcodes for inventory labels and product tagging.',
    category: 'text',
    icon: 'Barcode',
    tags: ['barcode', 'code128', 'inventory'],
    rating: 4.6,
    usageCount: 4500,
  },
  {
    id: 'text-base64',
    name: 'Base64 Encoder & Decoder',
    description: 'Encode or decode strings and binary data to/from standard Base64 format.',
    category: 'text',
    icon: 'Code2',
    tags: ['base64', 'encode', 'decode'],
    rating: 4.8,
    usageCount: 7900,
  },
  {
    id: 'text-json-formatter',
    name: 'JSON Formatter, Validator & Tree View',
    description: 'Format, minify, validate syntax, and inspect nested JSON objects in interactive tree format.',
    category: 'text',
    icon: 'FileCode',
    tags: ['json', 'formatter', 'validator', 'minify'],
    rating: 4.9,
    usageCount: 15100,
    popular: true,
  },
  {
    id: 'text-markdown-editor',
    name: 'Live Markdown Preview Editor',
    description: 'Write Markdown with real-time formatted preview and instant HTML / TXT export.',
    category: 'text',
    icon: 'Edit3',
    tags: ['markdown', 'editor', 'preview'],
    rating: 4.8,
    usageCount: 9200,
  },

  // --- CALCULATOR TOOLS ---
  {
    id: 'util-sci-calc',
    name: 'Full Advanced Scientific Calculator',
    description: 'Professional scientific math calculator with trigonometry (Deg/Rad), logarithms, powers, memory operations, live expression preview, calculation history, and formula references.',
    category: 'calculator',
    icon: 'Binary',
    tags: ['scientific', 'calculator', 'math', 'trigonometry', 'logarithm', 'algebra', 'calculus'],
    rating: 4.9,
    usageCount: 16800,
    popular: true,
  },
  {
    id: 'util-age-calc',
    name: 'Advanced Age Calculator Suite',
    description: 'Calculate exact age with live ticking seconds, next birthday countdown, zodiac sign, planetary ages, life milestones, and age comparison.',
    category: 'calculator',
    icon: 'CalendarDays',
    tags: ['age', 'calculator', 'birthday', 'zodiac', 'countdown', 'life', 'planets'],
    rating: 4.9,
    usageCount: 15800,
    popular: true,
  },
  {
    id: 'util-gst-calc',
    name: 'GST / Sales Tax Calculator',
    description: 'Calculate tax inclusive and exclusive net prices for commerce and invoicing.',
    category: 'calculator',
    icon: 'Receipt',
    tags: ['gst', 'tax', 'calculator', 'sales'],
    rating: 4.8,
    usageCount: 10800,
  },
  {
    id: 'util-emi-calc',
    name: 'Advanced Loan & EMI Calculator Suite',
    description: 'Calculate monthly loan EMI, interest vs principal breakdown, loan presets, prepayment savings, and full amortization schedule.',
    category: 'calculator',
    icon: 'Calculator',
    tags: ['emi', 'loan', 'finance', 'interest', 'amortization', 'home loan', 'car loan'],
    rating: 4.9,
    usageCount: 16500,
    popular: true,
  },
  {
    id: 'util-currency-calc',
    name: 'Real-Time Live Currency Converter',
    description: 'Live global exchange rates with quick swap, multi-currency conversion matrix, 25+ top world currencies (USD, INR, EUR, BDT, AED, etc.).',
    category: 'calculator',
    icon: 'DollarSign',
    tags: ['currency', 'exchange', 'forex', 'usd', 'inr', 'bdt', 'eur', 'gbp', 'live rate'],
    rating: 4.9,
    usageCount: 17800,
    popular: true,
  },
  {
    id: 'util-unit-calc',
    name: 'Universal Multi-Unit Converter',
    description: 'Instant unit conversion across Length, Weight, Temperature, Area, Volume, Speed, Data & Time with live comparison matrix.',
    category: 'calculator',
    icon: 'ArrowRightLeft',
    tags: ['unit', 'converter', 'length', 'weight', 'temperature', 'area', 'volume', 'speed', 'data', 'time'],
    rating: 4.9,
    usageCount: 15400,
    popular: true,
  },
  {
    id: 'util-percentage-calc',
    name: 'Advanced Percentage & Growth Calculator',
    description: 'Calculate percentage increase/decrease, % of a number, markup/discount, reverse percentage, and profit margin with step-by-step breakdown.',
    category: 'calculator',
    icon: 'Percent',
    tags: ['percent', 'increase', 'decrease', 'change', 'discount', 'markup', 'growth', 'margin'],
    rating: 4.9,
    usageCount: 14200,
    popular: true,
  },
  {
    id: 'util-bmi-calc',
    name: 'BMI & Fitness Health Calculator',
    description: 'Calculate Body Mass Index (BMI), BMR calorie needs, healthy weight range, and fitness category (Metric & Imperial).',
    category: 'calculator',
    icon: 'Scale',
    tags: ['bmi', 'health', 'fitness', 'weight', 'calorie', 'bmr', 'calculator'],
    rating: 4.9,
    usageCount: 13900,
    popular: true,
  },
  {
    id: 'util-gpa-calc',
    name: 'GPA & CGPA Grade Calculator',
    description: 'Calculate high school or university semester GPA, cumulative CGPA, grade point percentage, and class honors.',
    category: 'calculator',
    icon: 'GraduationCap',
    tags: ['gpa', 'cgpa', 'grade', 'marks', 'school', 'university', 'calculator'],
    rating: 4.8,
    usageCount: 11400,
  },
  {
    id: 'util-discount-calc',
    name: 'Shopping Discount & Savings Calculator',
    description: 'Calculate sale prices, percentage discounts, double stacked discounts, tax savings, and profit margins.',
    category: 'calculator',
    icon: 'Gift',
    tags: ['discount', 'sale', 'shopping', 'savings', 'profit', 'margin', 'calculator'],
    rating: 4.8,
    usageCount: 12200,
  },

  // --- UTILITY TOOLS ---
  {
    id: 'util-timer-stopwatch',
    name: 'Precision Stopwatch & Countdown Timer',
    description: 'Track lap times with split records or set countdown timers with audio sound alerts.',
    category: 'utility',
    icon: 'Clock',
    tags: ['stopwatch', 'timer', 'clock', 'alarm'],
    rating: 4.8,
    usageCount: 10100,
  },
  {
    id: 'util-calendar-planner',
    name: 'Interactive Calendar & Event Planner',
    description: 'View monthly calendar, plan events, set task reminders, and track key dates.',
    category: 'utility',
    icon: 'Calendar',
    tags: ['calendar', 'events', 'planner', 'schedule'],
    rating: 4.7,
    usageCount: 7400,
  },
  {
    id: 'util-uuid-gen',
    name: 'UUID / GUID v4 Batch Generator',
    description: 'Generate bulk random cryptographically unique UUID v4 identifiers for databases.',
    category: 'utility',
    icon: 'Cpu',
    tags: ['uuid', 'guid', 'developer', 'id'],
    rating: 4.8,
    usageCount: 8900,
  },
  {
    id: 'util-password-strength',
    name: 'Password Strength & Entropy Analyzer',
    description: 'Test password vulnerability, estimated crack time, entropy score, and security tips.',
    category: 'utility',
    icon: 'ShieldCheck',
    tags: ['password', 'security', 'strength', 'entropy'],
    rating: 4.7,
    usageCount: 6300,
  },
  {
    id: 'util-color-picker',
    name: 'Color Picker, Palette Generator & Contrast Check',
    description: 'Pick colors, generate matching color palettes, convert HEX/RGB/HSL, and test contrast accessibility.',
    category: 'utility',
    icon: 'Palette',
    tags: ['color', 'hex', 'palette', 'picker', 'rgb'],
    rating: 4.9,
    usageCount: 12800,
    popular: true,
  },
];
